### ISSUE TITLE
Cannot reload state

### ISSUE THREAD

**Issue by BreadAndRoses95** [alexvasilkov/GestureViews#113]
Hey, I'm trying to reload a state from one fragment to another one, but when calling getState().set(oldState) followed by AnimationKeepInBounds() or updateState() (even followed by resetState()) from my controller, it does not load the state properly (the zoom is different and the sometimes even the position). Do you have any idea where could it come from ?

**Comment by alexvasilkov** [comment]
Can't say for sure without code samples. It seems that something else is happening after you set the state that can affect it. Most probably it is:

* Layout changes. You should wait before your layout is ready, the state heavily depends on viewport area location and size, so it must be ready when you apply custom state.
* Image loading. The state also depends on the image size itself. Once an image is loaded it will reset the state, if image is updated (e.g. thumbnail is replaced with bigger image) it will update the state so that new image has same visual position.

**Comment by alexvasilkov** [comment]
How is it going here, have you fixed your issue?
