### ISSUE TITLE
Swipe up or down in ViewPager to exit

### ISSUE THREAD

**Issue by Yonezpt** [alexvasilkov/GestureViews#116]
I have been trying to follow the demo implementation of the ability to exit the ViewPager by swiping the image up or down, but had no success.
From what I understand this is somewhat tied to animations, but I cannot get to work.

I have my ViewPager in its own activity, it is an activity that only displays the GestureViewImages in that Viewpager, everything works, and all I want to do now is allow the user to slide up or down to finish the Activity, but I cannot find a clear explanation and the wiki does not contain that information.

**Comment by alexvasilkov** [comment]
You can find solution in this ticket: https://github.com/alexvasilkov/GestureViews/issues/58#issuecomment-277524111

But since library API is changed slightly since that I will post updated code here as well:

```Java
ViewsTransitionAnimator<Integer> animator =
           GestureTransitions.<Integer>fromNone().into(viewPager, new SimpleTracker() {
                @Override
                protected View getViewAt(int position) {
                    RecyclePagerAdapter.ViewHolder holder = adapter.getViewHolder(position);
                    return holder == null ? null : ViewPagerAdapter.getImage(holder);
                }
            });

animator.addPositionUpdateListener((position, isLeaving) -> {
    if (!isFinishing() && isLeaving
                && animator.getToView().getPositionAnimator().isAnimating()) {
        animator.getToView().getPositionAnimator().stopAnimation();
        finish();
    }
});

animator.enter(0, false);
```

Note, that `getViewAt(int position)` method should return `GestureImageView` of particular ViewPager page.

**Comment by Yonezpt** [comment]
Can't get this to work. I'm using the FragmentStatePagerAdapter for my view pager due to memory limitations/OOMEs since the method in your demos forced the creation of multiple views in a way that was more expensive than using the Fragments.

Every time the SimpleTracker is assigned, it tries to fetch the holder and fails because at that time no fragment is instantiated.

Is there a way to do this differently?

**Comment by alexvasilkov** [comment]
Dealing with Fragments in ViewPager is non-trivial, so I would recommend against such approach.

Demo app uses RecyclePagerAdapter (part of the lib) which should be much more memory efficient since it re-uses page views similar to how it is done in RecycleView. If you tried to use it then can you please share what issues you had with it exactly? The only advantage of the 
FragmentStatePagerAdapte that I see is that it saves and restores state for each page, but if your are not using this feature it will just be a waste of memory.

If you still want to deal with fragments then you'll need to wait for the first fragment to be created, or you can force its creation manually. But it is outside of the lib's scope, so you might need to search SO for answers.
