### ISSUE TITLE
The Image is clipped when the destination is inside a ScrollView

### ISSUE THREAD

**Issue by thierryd** [alexvasilkov/GestureViews#151]
If I put the destination inside a ScrollView, the image is clipped during the animation.

Is there anyway to avoid this clipping, or this is a limitation of the Library?

I have forked and modified the repo. See https://github.com/thierryd/GestureViews
The only modification is that I have added a ScrollView in demo_item_photo_full.xml

**Comment by alexvasilkov** [comment]
Thanks for reporting the issue and the example. I was able to reproduce and fix it.

The issue consists of 2 parts:
* You need to add `android:clipChildren="false"` to all non-fullscreen parent layouts (LinearLayout in this case).
* There was a bug in the library assuming that fullscreen image will always take full screen. It will be fixed in uncomming version.

**Comment by alexvasilkov** [comment]
New v2.6.0 will be available in few hours.

**Comment by thierryd** [comment]
It look fine now. Good work! :)
But....
If I set `clipChildren=false` in the parent LinearLayout, then zooming the image (by double tapping it) makes the image go outside its bounds (which make sense ;) )
So what I ended up doing is:
- Enable/Disable clip children only when we are animating
- If the image is zoomed in, then the animation from Fullscreen to the GridView is as follow:
-- Unzoom the image
-- Start the animation from Fullscreen to GridView

**Comment by alexvasilkov** [comment]
Yeah, indeed, removing clipping will make it look strange enough. But I think your solution is very good. I can enforce bounds clipping but exit animation will not look good anyway, so I can't see better options.
