### ISSUE TITLE
Cross-activity from recyclerview to viewpager?

### ISSUE THREAD

**Issue by huajianjiang** [alexvasilkov/GestureViews#154]
### FromActivity with Images RecyclerView transition to ToActivity with Image Viewer ViewPager.
It ends image blinking on activity start.
How to solve it?
Thanks!

**Comment by alexvasilkov** [comment]
Cross-activity animation is tricky, you have to synchronize positions in different activities and ensure that images loading library will instantly display the image in new activity.

I don't know what kind of a blinking issue you have since you didn't provide any code / images / videos. But please use #91 for this discussion. Meanwhile I'll close this issue as a duplicate, unless you believe there is a bug in the library itself and not in particular usage.
