### ISSUE TITLE
    java.lang.RuntimeException: Canvas: trying to draw too large(142674480bytes) bitmap.

### ISSUE THREAD

**Issue by qiandailu** [alexvasilkov/GestureViews#180]
http://cdn.5144wan.com/data/upload/image/20210310/ed2455d01fe349bf9a209ea606996364.jpg

**Comment by alexvasilkov** [comment]
This issue was reported a number of times: https://github.com/alexvasilkov/GestureViews/issues?q=is%3Aissue+too+large

The answer is still the same: this library does not render images, it just controls ImageView's drawing matrix. If you set a huge bitmap then the app will crash.
You might want to check your image loading library doesn't upscale images and that original image is small enough.
