### ISSUE TITLE
Question on Advanced Demo

### ISSUE THREAD

**Issue by sangwoo419** [alexvasilkov/GestureViews#20]
Hi, 

I recently encountered a problem where if list (the images) gets updated on ViewPager mode, the View Pager automatically exits and the RecyclerView gets updated. In other words, I want to update the list while I am in ViewPager mode. Do you have any idea why this might happen?

I also found that when I swipe horizontally in ViewPager mode, it sometimes exits by itself. Do you have any idea why this is happening? Lastly, if I use async instead of flickr would this cause a problem to the library?

Thank you for the support!

**Comment by sangwoo419** [comment]
Also, when I swipe horizontally in ViewPager mode, it sometimes exits by itself. Do you have any idea why this is happening?

Lastly, is it okay to replace flickr to async?

**Comment by alashow** [comment]
I had same problem. I fixed this just by synchronously updating adapters (recyclerView and viewPager).

For ex:
```
int oldSize = photosList.size();

photosList.addAll(newPhotos);
mPhotosAdapter.notifyItemRangeInserted(oldSize, newPhotos.size());
if (! mAnimator.isLeaving()) {
    mPagerAdapter.setPhotos(photosList);
}
```

**Comment by alexvasilkov** [comment]
Yes, most probably ViewPager is closed because there is no corresponding view in the underlying RecyclerView, updating ViewPager and RecyclerView adapters simultaneously should help. Although it is hard to say what is wrong in your case without source code.

Advanced demo uses pagination to load images from Flickr, and when you are swiping in ViewPager mode next page is loaded and updated in both RecyclerView and ViewPager without exiting from ViewPager mode.

Regarding flickr vs async question, I'm not sure I understand what exactly you want to achieve. Flickr is used only for demo purpose and you should replace it with your data, there are no requirements on how you should load your data.
