### ISSUE TITLE
Advanced Demo animation sometimes not working

### ISSUE THREAD

**Issue by sangwoo419** [alexvasilkov/GestureViews#24]
Hi,

This is probably the last question because we are almost done with our development. This is such an awesome library. Once again I really appreciate your work! Thank you so much.

We have one last bug that occurs somewhat often. Sometimes the advanced demo animation is not working. Basically, it is skipping the SharedElement-like animation and opening ViewPager mode. Do you have any idea why this is happening? 

Thanks!

**Comment by alexvasilkov** [comment]
Sorry for late response. Have you managed to fix this issue?

I probably had similar issue, it was caused by Glide's way to animate views, sometimes they are left hanging in the air (not bound to window), so library thinks they are not yet ready. You may try to fix it using custom animator like in [GlideHelper](https://github.com/alexvasilkov/GestureViews/blob/master/sample/src/main/java/com/alexvasilkov/gestures/sample/utils/glide/GlideHelper.java) class.

If it does not help consider next animation flow:
* You request animation for particular item (id / position)
* Using provided [ViewsTracker](https://github.com/alexvasilkov/GestureViews/blob/master/library/src/main/java/com/alexvasilkov/gestures/transition/ViewsTracker.java) objects library asks you to provide corresponding `to` and `from` views.
* Once **both** views are ready it starts enter animation.

So you may start by debugging if views are ready instantly or there is a delay.
