### ISSUE TITLE
ViewPager won't fling first few times

### ISSUE THREAD

**Issue by ZinoKader** [alexvasilkov/GestureViews#31]
I've noticed that on app launch, going through all my imageviews in the viewpager has a weird intercept when trying to fling between the views, but only the first time around, once you go through them all it no longer behaves like that.

Here is a video for reference:
[https://vid.me/Y4bU](https://vid.me/Y4bU)

**Comment by alexvasilkov** [comment]
Looks like view pager is re-layouted during scroll, which breaks current animation. GestureImageView should not cause re-layouting, so it may be something in your code.
Also I noticed that you set your own touch interceptor, which may also break scrolling.

**Comment by ZinoKader** [comment]
I'll try removing all interceptors except GIV. Thanks.

**Comment by MFlisar** [comment]
I have the same experience sometimes. It seems to happen with big images only (> HD resolution). I never experience something like that with smaller images... Any ideas where to look for the source reason here?

**Comment by MFlisar** [comment]
I made some additional observation: the problem seems to only (or at least much more conspicious and often) happen if an image is in landscape format...

**Comment by MFlisar** [comment]
I have a solution that works for me - it's just a complete different approach. Instead of using `image.getController().enableScrollInViewPager(viewPager);` on my `ViewPager` pages, I do NOT use this function but instead I use a custom `ViewPager`. It does not allow a fluid pan to change page transition, but the `ViewPager` seems to always work and seems to be much more responsive in my case...

I created a gist, if someone wants to check it and try it: https://gist.github.com/MFlisar/1ff2bc8bff94eabb52683ee53bf649eb

**Comment by ZinoKader** [comment]
I figured something like that should be possible but I just don't possess the knowledge to make my own custom viewpager. I'm glad you had a shot at it, I'm using it right now and it's great! Thanks MFlisar.
