### ISSUE TITLE
LAYER_TYPE_HARDWARE

### ISSUE THREAD

**Issue by MFlisar** [alexvasilkov/GestureViews#33]
I could not find something like `LAYER_TYPE_HARDWARE` in the code. I think, this could increase smoothness.

Whenever an animation is started you should call `view.setLayerType(View.LAYER_TYPE_HARDWARE, null);` and whenever it's finished you should call `view.setLayerType(View.LAYER_TYPE_NONE, null);`.

There's no listener to manually do that, is there?

**Comment by alexvasilkov** [comment]
I don't see any problems with smoothness, do you?
By default hardware acceleration already enabled, so you should not bother with layer types. If for some reason you have to force software rendering for your screen, then you probably better to apply hardware acceleration to gesture views once. Switching from software to hardware acceleration and back will most likely break animation smoothness.

**Comment by MFlisar** [comment]
Sometimes I see problems (little stutter), yes...

I've used the above technique with androids shared element transition successfully already, there it improved the smoothness... Just wanted to try it once, if possible...

**Comment by alexvasilkov** [comment]
As I said, hardware acceleration is already enabled by default. Try settings `android:hardwareAccelerated="false"` in your application tag in manifest and you will see how it works without acceleration (very buggy). So there is nothing to improve here.
If you wish you may experiment yourself, just use `PositionUpdateListener` as described in wiki.
BTW, if you think that stuttering is a real issue please create new ticket with video and possible steps to reproduce, I will look if I can do something (probably not, since there are too many places in the app that can cause it, i.e. images loading).

**Comment by MFlisar** [comment]
Ok, thanks for the informations
