### ISSUE TITLE
enableScrollInViewPager intercepts drawer dragging

### ISSUE THREAD

**Issue by ZinoKader** [alexvasilkov/GestureViews#36]
gestureImageView.getController().enableScrollInViewPager(pager) makes dragging out the drawer from the left impossible. Anyone got any ideas why?

**Comment by alexvasilkov** [comment]
This issue is hanging for almost 5 years now, but let me clarify two things:

* The way `enableScrollInViewPager` feature works requires to immediatelly intercept all parent touches so the drawer won't have a chance to receive touches and won't work. There is no workaround for it that I'm aware of unfortunatelly.
* It is not required to use `enableScrollInViewPager` feature, if you won't use it then drawer will start to work fine. The only downside is that you won't have a smooth image-panning to view-pager-panning transition. If the image is zoomed in the view pager (as well as drawer) won't do anything, if the image is zoomed out then both pager and drawer will start to work.
