### ISSUE TITLE
Enable Exit feature when gestures disabled

### ISSUE THREAD

**Issue by alashow** [alexvasilkov/GestureViews#50]
Currently, when the image is loading but has a preview (thumbnail, placeholder etc), users can't close images by swipe up/down gesture. Can you add a feature for exiting view even when gestures disabled? (`gestureImageView.getController().getSettings().disableGestures()`)

**Comment by alexvasilkov** [comment]
Not exactly, but now you can skip disabling gestures while waiting for full image loading. New image should just smoothly replace the old one even if it is zoomed/rotated and during exit gesture. See updated demo app. Note that in order to reset image state now you will need to set null as image drawable or reset it manually with `GestureController#resetState()`.

Let me know if it is enough to close this issue :)

**Comment by alashow** [comment]
But zooming while showing progress bar would look weird, wouldn't it?
I wasn't disabling gestures because of non-smooth replacement :)

**Comment by alexvasilkov** [comment]
Ok, makes sense, I will look into it later then

**Comment by alexvasilkov** [comment]
BTW, I checked sample app again (not yet in Play) which now does not disable gestures during full image loading, and it seems fine to me to show progress indicator while gestures are enabled. Thumbnails are usually small enough so that users cannot zoom it too much anyway and progress indicator looks just fine. So I think you can give it a try while this particular issue is not fixed.

**Comment by alexvasilkov** [comment]
I thought about this request for a while, but unfortunately it will require quite a lot of changes and will break backward compatibility, so I decided to skip this one.

You can probably achieve same behaviour by setting a very small max zoom value while loading bigger image, in this case you will not be able to zoom it in. Didn't test it myself though.
