### ISSUE TITLE
Exit with invisible view in recycler view

### ISSUE THREAD

**Issue by MFlisar** [alexvasilkov/GestureViews#54]
I have a `RecyclerView` with collapsible items, this means, when swiping through the view pager I may end up at a position where the `ViewsTracker` does not find a view in the `RecyclerView` because the item is collapsed (not part of the `RecyclerView` adapter items).

I tried using `animator.exit(false)` in this case, but even then the target view must exist in the `RecyclerView` and this results, that going back is not working in this case.

Any ideas how to solve that without completely skipping your animator?

**Idea**

In the special case of wanting to animate back to a collapsed item, the `ViewsTracker` for the `RecyclerView` returns -1 for `getPositionForId` (because the target item is not part of the adapter). IMHO, I think it (may?) be valid to go back without animation if the `ViewsTracker` tells the animator, that the `RecyclerView` does NOT contain the target view. It does not make sense to wait for a view to get ready in this case...

Alternatively it would be possible to animate this view to a pseudo position and rectangle, but I don't know how to do this with your classes. But this may be necessary for being able to close the view pager via a drag gesture.

**Comment by alexvasilkov** [comment]
This should be fixed in upcoming version.

It was alway be possible to return `ViewsTracker.NO_POSITION` in `getPositionForId()` callback, but in this case it was not possible to exit from such image.

In next release it is possible to start and finish animation from no image, means that animation will start from screen center (depends on gravity set in [Settings](https://github.com/alexvasilkov/GestureViews/wiki/Settings)), and all images for which we can find source image (return `NO_POSITION`) we will use this kind of animation.

**Comment by alexvasilkov** [comment]
[Version v2.3.0 is released](https://github.com/alexvasilkov/GestureViews/releases/tag/v2.3.0).
