### ISSUE TITLE
Using a GestureView exit between 2 activity

### ISSUE THREAD

**Issue by NitroG42** [alexvasilkov/GestureViews#59]
HEllo, sorry for this bug report as it's not a real bug, more of a question/feature request.
Your library is pretty great and easy to use, but I have a use case where I don't want to have the viewpager on the current activity, but rather on another one.

Transitions are still possible with Shared Elements https://github.com/codepath/android_guides/wiki/Shared-Element-Activity-Transition , is there a way to use that with the ViewsTransitionBuilder ? 
Probably not but my real problem is, if can go without enter transition, the Exit one is already pretty great, but I couldn't find a way to bypass the "enter" transition and use only the exit one.... do you have any lead ?

**Comment by alexvasilkov** [comment]
Yes, you can animate images from one activty to another.
I added separate sample for this case, check [Ex7CrossActivityFrom](https://github.com/alexvasilkov/GestureViews/blob/ab6eb838/sample/src/main/java/com/alexvasilkov/gestures/sample/activities/Ex7CrossActivityFrom.java) and [Ex7CrossActivityTo](https://github.com/alexvasilkov/GestureViews/blob/ab6eb838/sample/src/main/java/com/alexvasilkov/gestures/sample/activities/Ex7CrossActivityTo.java).

You can bypass "enter" animation by using `enter(false)`, in this case image will be "entered" without animation. But you still have to call `enter(...)` method if you want to animate exit back to source's image position.

Another option (depends on your usecase) is to start animation from no specific image, this can be done as follow:
`GestureTransitions.fromNone().into(...).enter(...);`
In this case animation will start from screen center instead of source image location.

**Comment by alexvasilkov** [comment]
Note though, that it will only be availbe in next version, which should hopefully be released soon.
