### ISSUE TITLE
Crash on API 19

### ISSUE THREAD

**Issue by fedeamura** [alexvasilkov/GestureViews#66]
2 things:
 1 - The sample APK is not working on API 19.
 2 - I add the library (v 2.2.0) to a project. I have a recycler view and a view pager. On API 19 > is working great. But in API 19, when i rotate the device, the app crashes, and i have not log. Its very strange. The error occurs when the recyclerview render. If i set "view.Gone" to the visibility of the recyclerview, the apps not crashes.

Thanks!

**Comment by alexvasilkov** [comment]
1. Fixed (but not in play store yet).
The issue was in context casting, on Android 19 view's context was not actually an activty itself.
Note though, that it was a problem of sample app, not of the library itself.

2. You can't have no logs actually, probably you just need to adjust logs filtering in Android Monitor.
Without the logs and sample of your code there is little I can do. If you'll find out that this issue leads into the lib's code then please create a new github issue with detailed explanation.
