### ISSUE TITLE
GestureImageViews shapes.

### ISSUE THREAD

**Issue by Khunchheang** [alexvasilkov/GestureViews#67]
Currently I work with many shapes of ImageView. So Can GestureImageViews work as round shape?

**Comment by alashow** [comment]
See [this](https://github.com/alexvasilkov/GestureViews/blob/master/sample/src/main/java/com/alexvasilkov/gestures/sample/activities/Ex4SingleImageAnimationActivity.java#L77)

**Comment by Khunchheang** [comment]
Can you show me about problem below: 
java.lang.RuntimeException: For better performance only BitmapDrawables are supported, but you can override getBitmapFromDrawable() and build bitmap on your own

**Comment by alexvasilkov** [comment]
Image rounding uses `BitmapShader` for performance optimization. So in order to round the image it needs to directly use bitmap instance.

It is possible to create bitmap from any drawable manually, but it will require unnecessary memory pressure, so this feature was not implemented intentionally.

By default library only supports `BitmapDrawable`, but if you know how to extract bitmap instances from your drawables or you want to generate bitmaps for any drawables then you have to override both `CircleImageView` and `CircleGestureImageView` and provide your implementation of `getBitmapFromDrawable(Drawable)` method.

If you use Glide then another option would be to just use `Glide.with(...).load(...).asBitmap()`.
