### ISSUE TITLE
How to create with different lists

### ISSUE THREAD

**Issue by lanetteamtapan** [alexvasilkov/GestureViews#70]
I have to different list in recyclerview and viewpager, I just want drag to close animation i don't want the position to be maintained is it possible?

**Comment by alexvasilkov** [comment]
Not sure what you mean by "don't want the position to be maintained".

You can try to return `FromTracker.NO_POSITION` in `getPositionById()` methods of your `FromTracker` and `IntoTracker` for all items for which you don't want / can't return real positions. 

If there were no "from view" / "to view" pair found (because you returned `NO_POSITION`) then no position animation will be played for image and it will just zoom out to the center of the screen.

**Comment by lanetteamtapan** [comment]
@alexvasilkov  thanks it works for me
