### ISSUE TITLE
How to use library with nested RecyclerViews?

### ISSUE THREAD

**Issue by geared554** [alexvasilkov/GestureViews#73]
For example I have a list of complex items in a recycler. Every item can contain or not contain nested recycler with undetermined amount of items. 

I would like to open ViewPager with opening and closing animations only for one item's image list.

In general it looks like this (I filled recyclers with yellow and items with light blue):
![2017-06-26 17 27 14](https://user-images.githubusercontent.com/4698222/27544180-0679440e-5a95-11e7-9b50-06eaee6be4bd.png)

1. How to use all the GestureViews' magic in this case?
2. Is it possible to show and correctly animate closing in case of showing in VP all of images available in parent recycler?

**Comment by alexvasilkov** [comment]
This is a good question, thanks. I really hope to improve documentation one day and cover such cases.

You can find an introduction on [this wiki page](https://github.com/alexvasilkov/GestureViews/wiki/Advanced-animations).

In order to archive this behavior you will need next:

1. Create animator as usual:

```java
animator = GestureTransitions.from(recyclerView, fromTracker).into(viewPager, intoTracker);
```
We'll get back to `fromTracker` and `intoTracker` a bit later.

2. Once image is clicked in a particular list item we need to get both position of this list item (`itemPos`) and id of clicked image (`imageId`).

`itemPos` should be stored as activity (or fragment) field, so that it is accessible from `fromTracker` (see next).

Note, that if item position was changed for any reason it should be updated to a correct one or set to `FromTracker.NO_POSITION` if given item is not present in the list anymore.

It is also possible to use images positions instead of ids, but only if images order will never change.

3. Now `fromTracker` should be implemented as follow:

```java
final FromTracker<ID> fromTracker = new FromTracker<ID>() {
    @Override
    public View getViewById(ID imageId) {
        // Return view of the image inside current list item or null if the image is not
        // present as a view inside the item (but it can exist in a full images list which
        // will be shown in ViewPager).
        // So basically you should get ViewHolder object from RecyclerView using itemPos
        // and then ask adapter to find required image view in it.

        final RecyclerView.ViewHolder holder =
                    recyclerView.findViewHolderForLayoutPosition(itemPos);
        return holder == null ? null : recyclerAdapter.getImageView(holder, imageId);
    }

    @Override
    public int getPositionById(ID imageId) {
        // If item on position `itemPos` is not currently visible (its ViewHolder is null)
        // then we should return `itemPos`, so that GestureViews lib will auto-scroll
        // to it first. If item is visible then we should return `itemPos` if we have
        // a view for the image and `FromTracker.NO_POSITION` if there is no view
        // for the image.

        final boolean hasHolder =
                    views.list.findViewHolderForLayoutPosition(selectedPosition) != null;
        return !hasHolder || getViewById(imageId) != null
                        ? selectedPosition : FromTracker.NO_POSITION;
    }
}
```

4. `intoTracker` should be implemented as usually, and if images order is unchanged then we can use `SimpleTracker`:

```java
final SimpleTracker intoTracker = new SimpleTracker() {
            @Override
            public View getViewAt(int pos) {
                final RecyclePagerAdapter.ViewHolder holder = pagerAdapter.getViewHolder(pos);
                return holder == null ? null : pagerAdapter.getImage(holder);
            }
        };
```

5. Now once image is clicked we should set images list into ViewPager's adapter, and then start the animation:

```java
public void onImageClick(Item item, int itemPos, int imageId) {
    this.itemPos = itemPos;
    pagerAdapter.setImages(item.getImages());
    animator.enter(imageId, true);
}
```

**Comment by alexvasilkov** [comment]
Note, that if some images are present in pager but not in the list view they will be animated to the screen center when closed.

**Comment by geared554** [comment]
Thanks for your answer. 
As I understand I need to create _only one_ animator instance in container (`Activity` or `Fragment`) and find exact nested `RecyclerView` and exact image in this view using `fromTracker`. Seems that ID used in `fromTracker` in this case must be combined from both of ids (fro example `Pair<Integer, Integer>`). So how could I create such ID to pass it to `fromTracker`?

**Comment by alexvasilkov** [comment]
I committed new example in a separate branch, you can check it [here](https://github.com/alexvasilkov/GestureViews/tree/complex_list_ex/sample/src/main/java/com/alexvasilkov/gestures/sample/ui/ex8), not sure if it will be part of master.

You will need only one animator and you won't need to combine ids.

**Comment by geared554** [comment]
Thank you! This example really helped!

**Comment by alexvasilkov** [comment]
Good, please close the issue if you feel it is solved for you.
