### ISSUE TITLE
Gesture support for RecyclerView

### ISSUE THREAD

**Issue by Saketme** [alexvasilkov/GestureViews#78]
Hey @alexvasilkov, will it be possible to add support for horizontally scrolling RecyclerViews? RV now supports snapping to items so I'd prefer using it instead of ViewPager because doing item animations is easier.

**Comment by alexvasilkov** [comment]
There are a few things to consider when adding support for `RecyclerView`:
* Smooth scrolling within `RecyclerView` item that should also trigger `RecyclerView` scrolling once we reached left or right edge.
* `RecyclerView` item can be smaller than screen width, so that other items are also shown on the sides. That means that we should also animate these items somehow to make it look good.

And it is quite a lot of work. Personally I can't see lots of advantages of `RecyclerView` over `ViewPager`, at least in case of displaying full screen images / layouts.

**Comment by Saketme** [comment]
No problem, thanks!
