### ISSUE TITLE
Android Studio 3.0 couldn't import project with gradle problem

### ISSUE THREAD

**Issue by ZhouKanZ** [alexvasilkov/GestureViews#99]
error Message:

Error:FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\Administrator\Desktop\GestureViews\sample\release.gradle' line: 47

* What went wrong:
A problem occurred configuring project ':sample'.
> Task with name 'packageRelease' not found in project ':sample'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

i'm not familiar with gradle , If you can, help me check what went wrong

**Comment by ZhouKanZ** [comment]
another question . in this project, i want to move imageView free instead of limitted in a special area

**Comment by alexvasilkov** [comment]
Hm, that's hard to debug with provided information.

I can say for sure that clean build should work just fine (e.g. check [latest Travis build](https://travis-ci.org/alexvasilkov/GestureViews)).

Basically you have something misconfigured in your build script so that `packageRelease` task is not created for you.
Try a clean checkout and make sure you are using latest version of the repo. You may also need to use Android Studio 3, but I doubt it can be a problem even if you'll use older AS.

**Comment by alexvasilkov** [comment]
Hm, `packageRelease` is a standard task, I don't really know why it cannot find it.

Did you change anything in the code before you started the build, or you are just building the latest version without own modifications?

As a workaround you may try to remove `apply from: 'release.gradle'` from sample's `build.gradle` script.
